var a = Math.random() ;
b = a * 6 ;
c = Math.floor(b) ;
// dice1 = d
d = c + 1 ;
var e = Math.random() ;
f = e * 6 ;
g = Math.floor(f) ;
// dice2 = h
h = g + 1 ;
if (d === 1 && h === 1) {
  document.querySelector("#background").innerHTML ="<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 1 && h === 2) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 1 && h === 3) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 1 && h === 4) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 1 && h === 5) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 1 && h === 6) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'>.</span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 2 && h === 1) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 2 && h === 2) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 2 && h === 3) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 2 && h === 4) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 2 && h === 5) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 2 && h === 6) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'>.</span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 3 && h === 1) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 3 && h === 2) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 3 && h === 3) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 3 && h === 4) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 3 && h === 5) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 3 && h === 6) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'></span></td><td colspan='5'><span class='dots2'>.</span></td><td colspan='5'><span class='dots3'></span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'></span></td><td colspan='5'><span class='dots8'>.</span></td><td colspan='5'><span class='dots9'></span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'>.</span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 4 && h === 1) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 4 && h === 2) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 4 && h === 3) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 4 && h === 4) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 4 && h === 5) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 4 && h === 6) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'>.</span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 5 && h === 1) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 5 && h === 2) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 5 && h === 3) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 5 && h === 4) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 5 && h === 5) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 5 && h === 6) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'></span></td><td colspan='5'><span class='dots5'>.</span></td><td colspan='5'><span class='dots6'></span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'>.</span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 6 && h === 1) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'>.</span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'>.</span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 6 && h === 2) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'>.</span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'>.</span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 6 && h === 3) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'>.</span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'>.</span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'></span></td><td colspan='5'><span class='dots11'>.</span></td><td colspan='5'><span class='dots12'></span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'></span></td><td colspan='5'><span class='dots17'>.</span></td><td colspan='5'><span class='dots18'></span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 6 && h === 4) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'>.</span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'>.</span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
else if (d === 6 && h === 5) {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'>.</span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'>.</span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'></span></td><td colspan='5'><span class='dots14'>.</span></td><td colspan='5'><span class='dots15'></span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
} else {
  document.querySelector("#background").innerHTML = "<table><tr><td><div class='left'><span id='dice1'><table><tr><td colspan='5'><span class='dots1'>.</span></td><td colspan='5'><span class='dots2'></span></td><td colspan='5'><span class='dots3'>.</span></td></tr><tr><td colspan='5'><span class='dots4'>.</span></td><td colspan='5'><span class='dots5'></span></td><td colspan='5'><span class='dots6'>.</span></td></tr><tr><td colspan='5'><span class='dots7'>.</span></td><td colspan='5'><span class='dots8'></span></td><td colspan='5'><span class='dots9'>.</span></td></tr></table></span></div></td><td><div class='right'><span id='dice2'><table><tr><td colspan='5'><span class='dots10'>.</span></td><td colspan='5'><span class='dots11'></span></td><td colspan='5'><span class='dots12'>.</span></td></tr><tr><td colspan='5'><span class='dots13'>.</span></td><td colspan='5'><span class='dots14'></span></td><td colspan='5'><span class='dots15'>.</span></td></tr><tr><td colspan='5'><span class='dots16'>.</span></td><td colspan='5'><span class='dots17'></span></td><td colspan='5'><span class='dots18'>.</span></td></tr></table></span></div></td></tr></table><div class='roll'><a href='index.html'><button type='button' class='btn btn-outline-secondary btn btn-secondary btn-lg'>Roll</button></a></div>";
}
